# 🌧️ Raining Tables 🌧️ {.unnumbered}

Hey, analyst! Welcome to 🌧️ **Raining Tables** 🌧️, a precipitation- and plumbing-themed package that puddle-jumps through a minimal data pipeline. 

In this package, we're hooking up a [daily precipitation](https://www.ncei.noaa.gov/cdo-web/search?datasetid=GHCND) table so live data can flow through NOAA's public API to our environment and out to databases and dashboards. We'll: 

- read in a spreadsheet, 
- explore various ways to output it (csv, Excel, PDF), 
- pull data updates from NOAA's API (thanks, NOAA!), 
- read out to a database, 
- weatherproof with basic testing and maintenance, 
- save our outputs to Google Drive, 
- create a simple dashboard, 
- put all our code in a container, and 
- run it from ☁️ _the cloud._ ☁️

By walking through these steps, this package aims to help you understand your script as part of an automated analytical pipeline, one that might flow from: 

    Public data APIs > Report templates > Databases
                                        > APIs > Dashboards
                                        > Excel/PDFs/other outputs > Google Drive
                                        > Containers > Cloud

# Credits & Disclaimers

🌧️ Raining Tables 🌧️ is *not* intended to teach you to code. A variety of teaching tools are available for learning to code. Code syntax is unlikely to be your bottleneck these days, particularly with the advent of Claude Code and other AI tools. 

Views my own and do not reflect the views of any current or prior employer.
I receive no compensation for this blog or any recommended resources on it.

**🌧️ Raining Tables 🌧️ Data Credits:**

Daily summaries from NOAA's [National Centers for Environmental Information](https://www.ncei.noaa.gov/)'s [Global Historical
Climatology Network](https://www.ncei.noaa.gov/access/search/data-search/daily-summaries).
You all are awesome ❤️ Weather data is critical infrastructure. 

Formal data citation:

Menne, M.J., I. Durre, B. Korzeniewski, S. McNeill, K. Thomas, X. Yin, S. Anthony, R. Ray, 
R.S. Vose, B.E.Gleason, and T.G. Houston, 2012: Global Historical Climatology Network - 
Daily (GHCN-Daily), Version 3.34.
NOAA National Climatic Data Center. http://doi.org/10.7289/V5D21VHZ. July 2026.

**🌧️ Raining Tables 🌧️ Image Credits:**

Seattle Space Needle: [S_Donald at pixabay](https://pixabay.com/photos/seattle-waterfront-washington-5364650/).